config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update] do
    resources :animals, only: [:new, :create, :edit, :update]
  end

  resources :animals, only: [:show, :destroy, :index] do
    resources :adoptions, only: [:new, :create]
  end
 
  resource :search, only: [:show]
  resources :payments, only: [:new, :create]

  resources :adoptions, only: [:index, :show, :destroy] do
    resources :feedings, only: [:create]
    resources :plays, only: [:create]
    resources :trainings, only: [:create]
    resources :sleeps, only: [:create]
  end

  get "/sign_up", to: "users#new"
  get "/sign_in", to: "sessions#new"
  get "/", to: "dashboards#show", as: :dashboard
  root to: "dashboards#show"
end

app/models/dashboard.rb
class Dashboard
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @adoption = current_user.adoption
    @payment = Payment.new
    if current_user.adoption
      @animal = Animal.find(@adoption.animal_id)
      @adoption.level_up
    end
  end
end

app/views/dashboards/_stripe_form.html.erb
<%= form_for @payment, html: {id: "new_payment"} do |form| %>
  <div>
    <%= form.label :credits %>
    <%= form.number_field :credits, value: 0 %>
  </div>
  
  <%= form.hidden_field :stripe_card_token, id: "stripe_card_token" %>

  <div>
    <%= label_tag :card_number, "Credit Card Number" %>
    <%= text_field_tag :card_number, nil, name: nil, id: "card_number" %>
  </div>
  <div>
    <%= label_tag :card_code, "Security Code on Card (CVV)" %>
    <%= text_field_tag :card_code, nil, name: nil, id: "card_code" %>
  </div>
  <div>
    <%= label_tag :card_month, "Card Expiration" %>
    <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
    <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  </div>
  <div id="stripe_error">
  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  <%= form.submit "Purchase more credits" %>
<% end %>

app/views/dashboards/show.html.erb
<% if current_user.adoption %>
  <%= render @adoption %>
<% elsif current_user.shelter? %>
  <div class="shelter-container">
      <%= form_tag edit_user_path(current_user), method: :get do %>
      <%= submit_tag "Edit User", class: "button" %>
      <% end %>
      
      <%= form_tag new_user_animal_path(current_user), method: :get do %>
      <%= submit_tag "Create Animal Listing", class: "button" %>
      <% end %>

      <%= form_tag animals_path, method: :get do %>
        <%= submit_tag "View my animal listings", class: "button" %>
      <% end %>

      <a href="#" class="button">Upload Business Verification</a>
  </div>
<% else %>
  <div class="dashboard-container">
  <h2>Hello <%= current_user.name.capitalize %>.</h2>
  <h4>Enter your address, and browse adoptable pets near you!</h4>

  <%= form_tag search_path, method: :get do %>
    <%= text_field_tag :query %>
    <%= submit_tag "Search", class: "button" %>
  <% end %>
<% end %>
</div>