config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update] do
    resources :animals, only: [:new, :create, :edit, :update]
  end

  resources :animals, only: [:show, :destroy, :index] do
    resources :adoptions, only: [:new, :create]
  end
 
  resource :search, only: [:show]
  resources :payments, only: [:new, :create]

  resources :adoptions, only: [:index, :show, :destroy] do
    resources :feedings, only: [:create]
    resources :plays, only: [:create]
    resources :trainings, only: [:create]
    resources :sleeps, only: [:create]
  end

  get "/sign_up", to: "users#new"
  get "/sign_in", to: "sessions#new"
  get "/", to: "dashboards#show", as: :dashboard
  root to: "dashboards#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", "application", "vendor/modernizr", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC_KEY %>
    <title>Fluffy</title>
  </head>
  <body>
    <div>
      <nav class="top-bar" data-topbar>
      <section class="top-bar-section">
        <ul class="right">
          <li class="has-dropdown">
          <% if current_user.adoption %>
            <a href="#">Options</a>
              <ul class="dropdown">
                <li><%= link_to "Abandon Pet", @adoption, method: :delete %></li>
              </ul>
          </li>
          <li class="active"><%= link_to "Purchase Credits", [:new, :payment] %></a></li>
        <% end %>
      </ul>

        <ul class="left">
          <li><%= link_to "Fluffy", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Sign out", session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign in", new_session_path %></li>
            <li><%= link_to "Sign up", new_user_path %></li>
          <% end %>
        </ul>
      </div>

      <div class="outer-container">
       <%= yield %>
    </div>
  </body>
</html>